import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class ConnectingTheDotsMain extends JFrame implements ActionListener, MouseListener {
	private JFrame frame;
	private JButton btnSave;
	private JButton btnLoad;
	private JButton btnAutogenerateDots;
	private JPanel grid;
	private JButton btnClear;
	private JButton btnRun;
	private Graphics graphics;
	private int circleDiameter = 10;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					ConnectingTheDotsMain window = new ConnectingTheDotsMain();
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public ConnectingTheDotsMain() {
		initialize();
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		frame = new JFrame();
		frame.setTitle("Connecting the Dots");
		frame.setBounds(100, 100, 679, 494);
		frame.setResizable(false);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.getContentPane().setLayout(null);

		btnSave = new JButton("Save");
		btnSave.setFont(new Font("Tahoma", Font.BOLD, 14));
		btnSave.setBounds(588, 10, 70, 32);
		btnSave.addActionListener(this);
		frame.getContentPane().add(btnSave);

		btnLoad = new JButton("Load");
		btnLoad.setFont(new Font("Tahoma", Font.BOLD, 14));
		btnLoad.setBounds(511, 10, 70, 32);
		btnLoad.addActionListener(this);
		frame.getContentPane().add(btnLoad);

		btnClear = new JButton("Clear");
		btnClear.setFont(new Font("Tahoma", Font.BOLD, 14));
		btnClear.setBounds(357, 10, 100, 32);
		btnClear.addActionListener(this);
		frame.getContentPane().add(btnClear);

		btnRun = new JButton("Run");
		btnRun.setFont(new Font("Tahoma", Font.BOLD, 14));
		btnRun.setBounds(187, 10, 70, 32);
		btnRun.addActionListener(this);
		frame.getContentPane().add(btnRun);

		grid = new JPanel();
		grid.setBackground(Color.WHITE);
		grid.setBounds(10, 52, 645, 395);
		grid.addMouseListener(this);
		frame.getContentPane().add(grid);

		btnAutogenerateDots = new JButton("Auto-Generate Dots");
		btnAutogenerateDots.setFont(new Font("Tahoma", Font.BOLD, 12));
		btnAutogenerateDots.setBounds(10, 10, 167, 32);
		btnAutogenerateDots.addActionListener(this);
		frame.getContentPane().add(btnAutogenerateDots);
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		
	}
	
	/**
	 * This method draws dots on the panel
	 * 
	 * @param x
	 * @param y
	 */
	private void drawDots(int x, int y) {
		graphics = grid.getGraphics();
		graphics.fillOval(x, y, circleDiameter, circleDiameter);
	}
	
	@Override
	public void mouseClicked(MouseEvent e) {
		int x = e.getX();
		int y = e.getY();
		this.drawDots(x, y);
	}

	@Override
	public void mousePressed(MouseEvent e) {
	}

	@Override
	public void mouseReleased(MouseEvent e) {
	}

	@Override
	public void mouseEntered(MouseEvent e) {
	}

	@Override
	public void mouseExited(MouseEvent e) {
	}

}
